# NAME: Jeffrey Chan
# EMAIL: jeffschan97@gmail.com
# ID: 004-611638

.SILENT:

default: dist

clean:
	rm -f hello *.tar.gz

dist:
	tar -czvf lab4a-004611638.tar.gz edison-selfie.jpg \
	ifconfig.png scp.png git-clone.png compilation.png README
