# NAME: Jeffrey Chan
# EMAIL: jeffschan97@gmail.com
# ID: 004-611-638

.SILENT:

default:
	gcc -g lab1a.c -o lab1a

clean:
	rm -f *.tar.gz lab1a

dist:
	tar -czvf lab1a-004611638.tar.gz Makefile README lab1a.c
