# NAME: Jeffrey Chan, Jiwan Kang
# EMAIL: jeffschan97@gmail.com, jiwan226@gmail.com
# ID: 004-611-638, 704-624-623

.SILENT:

default:
	echo "python compiled successfully" > /dev/null

clean:
	rm -f *.tar.gz

dist:
	tar -czf lab3b-004611638.tar.gz Makefile README lab3b.py lab3b
