# NAME: Jeffrey Chan
# EMAIL: jeffschan97@gmail.com
# ID: 004-611-638

.SILENT:

default: build

build:
	gcc -pthread -lrt -o lab2a-add -g lab2a-add.c

tests:
	echo "tests target"

graphs:
	echo "graphs target"

clean:
	rm -f *.tar.gz

dist:
	tar -czf lab2a-004611638.tar.gz Makefile
