# NAME: Jeffrey Chan
# EMAIL: jeffschan97@gmail.com
# ID: 004-611-638

.SILENT:

default:
	gcc -lmraa -lm lab4b.c -o lab4b

check:
	echo "check target"

clean:
	rm -f lab4b *.txt

dist:
	tar -czf lab4b-004611638.tar.gz Makefile README
