# NAME: Jeffrey Chan
# EMAIL: jeffschan97@gmail.com
# ID: 004-611-638

.SILENT:

default:
	gcc -lmraa -lm -g lab4b.c -o lab4b

check:
	./testscript.sh

clean:
	rm -f lab4b *.txt *.tar.gz

dist:
	tar -czf lab4b-004611638.tar.gz Makefile README lab4b.c
