# NAME: Jeffrey Chan, Jiwan Kang
# EMAIL: jeffschan97@gmail.com, jiwan226@gmail.com
# ID: 004-611-638, 704-624-623

.SILENT:

default:
	gcc -g lab3a.c -o lab3a

clean:
	rm -f lab3a *.tar.gz *.csv

dist:
	tar -czf lab3a-004611638.tar.gz Makefile README ext2_fs.h lab3a.c
