# NAME: Jeffrey Chan, Jiwan Kang
# EMAIL: jeffschan97@gmail.com,
# ID: 004-611-638,

.SILENT:

default:
	gcc -g lab3a.c -o lab3a

clean:
	rm -f lab3a *.tar.gz

dist:
	tar -czf lab4b-004611638.tar.gz Makefile README
