# NAME: Jeffrey Chan
# EMAIL: jeffschan97@gmail.com
# ID: 004-611-638

.SILENT:

default: build

build:
	gcc -pthread -lrt -o lab2_list -g SortedList.c lab2_list.c

clean:
	rm -f *.tar.gz

dist:
	tar -czf lab2b-004611638.tar.gz Makefile README 
